import { DatabaseState } from "../types";

export const DEFAULT_DB_STATE: DatabaseState = {
  generalSettings: {
    logoUrl: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&q=80&w=200",
    titleEn: "Free Student Union - DMC",
    titleNp: "Free Student Union - DMC",
    subtitleEn: "Darchula Multiple Campus, Khalanga, Darchula",
    subtitleNp: "Darchula Multiple Campus, Khalanga, Darchula",
    aboutFsuEn: "The Free Student Union (FSU) of Darchula Multiple Campus is a democratic student body dedicated to representing student voices, fostering academic excellence, and leading constructive campus welfare and social programs. Established with the vision of promoting student rights, the FSU plays a pivotal role in maintaining academic standards, organizing extracurricular activities, and acting as a bridge between campus administration and students. We actively engage in community services, sports, cultural programs, and academic forums.",
    aboutFsuNp: "The Free Student Union (FSU) of Darchula Multiple Campus is a democratic student body dedicated to representing student voices, fostering academic excellence, and leading constructive campus welfare and social programs.",
    aboutFsuImg: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=800",
    aboutCampusEn: "Darchula Multiple Campus (DMC), established in 2062 BS, is a premier higher education institution in the far-western mountain district of Darchula, Nepal. Proudly affiliated with Farwestern University (fwu.edu.np), DMC provides accessible, quality education in Humanities, Management, and Education streams to students from remote communities. It is committed to fostering academic competence, moral values, and social responsibility under the leadership of dedicated faculties and campus management.",
    aboutCampusNp: "Darchula Multiple Campus (DMC), established in 2062 BS, is a premier higher education institution in the far-western mountain district of Darchula, Nepal, proudly affiliated with Farwestern University (fwu.edu.np).",
    aboutCampusImg: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=800",
    presidentNameEn: "Amit Joshi",
    presidentNameNp: "Amit Joshi",
    presidentPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    presidentMessageEn: "Dear fellow students, it is an absolute honor to lead the Free Student Union at Darchula Multiple Campus. Our FSU is committed to creating an inclusive, vibrant, and progressive academic environment. We are focused on strengthening student facilities, organizing academic seminars, modernizing our library, and expanding sports initiatives. Let us work hand in hand to make our campus a hub of excellence and standard education.",
    presidentMessageNp: "Dear fellow students, it is an absolute honor to lead the Free Student Union at Darchula Multiple Campus.",
    chiefNameEn: "Campus Chief",
    chiefNameNp: "Campus Chief",
    chiefPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200",
    chiefMessageEn: "Welcome to Darchula Multiple Campus. As the Campus Chief, I am proud of our academic legacy and the synergy we share with our vibrant student community and the FSU. We strive to provide standard higher education under Farwestern University using modern teaching methodologies, and we continuously support our students in academic and extra-curricular paths.",
    chiefMessageNp: "Welcome to Darchula Multiple Campus.",
    fbCampusPage: "https://facebook.com/DarchulaMultipleCampusOfficial",
    fbFsuPage: "https://facebook.com/amitjoc",
    privacyPolicyEn: "This Privacy Policy governs the manner in which the Free Student Union - DMC Portal collects, uses, maintains and discloses information collected from users. Your privacy is extremely important to us, and any data submitted via the anonymous or standard contact form is securely stored with restricted, authenticated administration access.",
    privacyPolicyNp: "This Privacy Policy governs the manner in which the Free Student Union - DMC Portal collects, uses, maintains and discloses information collected from users.",
    termsEn: "By accessing this portal, you agree to use it strictly for academic, inquiry, and constructive feedback purposes. Any spamming of the contact system or unauthorized attempts to access administrative pages is strictly prohibited and subject to institutional discipline.",
    termsNp: "By accessing this portal, you agree to use it strictly for academic, inquiry, and constructive feedback purposes.",
    dmcHistoryHeading: "History of Darchula Multiple Campus",
    dmcHistoryText: "Darchula Multiple Campus (DMC), established in 2062 B.S. (2005 A.D.), stands as the premier higher education beacon in the far-western Himalayan district of Darchula, Nepal. Affiliated with Farwestern University (FWU), the campus was established through the collective vision and relentless dedication of local educators, intellectuals, and community leaders to make quality university education accessible to students in remote mountainous terrain.\n\nOver the past two decades, DMC has expanded its academic horizons across Education, Humanities, and Management streams. DMC continues to cultivate academic excellence, moral integrity, and social leadership among Himalayan youth.",
    dmcEstYear: "Est. 2062 B.S. (2005 A.D.)",
    dmcFacebookProfileUrl: "https://facebook.com/DarchulaMultipleCampusOfficial",
    dmcFacebookButtonText: "Visit Official Facebook Profile",
  },
  slides: {
    "slide_1": {
      id: "slide_1",
      imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1200",
      titleEn: "Welcome to Free Student Union - DMC",
      titleNp: "Welcome to Free Student Union - DMC"
    },
    "slide_2": {
      id: "slide_2",
      imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=1200",
      titleEn: "Empowering Students, Transforming Futures",
      titleNp: "Empowering Students, Transforming Futures"
    },
    "slide_3": {
      id: "slide_3",
      imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=1200",
      titleEn: "Affiliated to Farwestern University (fwu.edu.np)",
      titleNp: "Affiliated to Farwestern University (fwu.edu.np)"
    }
  },
  news: {
    "news_1": {
      id: "news_1",
      headingEn: "BBS and B.Ed Examination Schedule Published by Farwestern University",
      headingNp: "BBS and B.Ed Examination Schedule Published by Farwestern University",
      bodyEn: "Farwestern University Examination Controller has officially published the examination schedules for BBS and B.Ed programs. All students are advised to check the timetable and collect their admit cards from the campus administration. Best wishes for your examinations!",
      bodyNp: "Farwestern University Examination Controller has officially published the examination schedules for BBS and B.Ed programs.",
      imageUrl: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=600",
      createdAt: 1784534400000
    },
    "news_2": {
      id: "news_2",
      headingEn: "FSU to Organize District Level Inter-College Sports Meet",
      headingNp: "FSU to Organize District Level Inter-College Sports Meet",
      bodyEn: "To promote sportsmanship and healthy physical well-being, the Free Student Union - DMC is organizing a district-level Inter-College Cricket and Volleyball tournament. Teams from higher secondary institutions across Darchula are cordially invited. Registration forms are available at the FSU secretariat.",
      bodyNp: "FSU to Organize District Level Inter-College Sports Meet",
      imageUrl: "https://images.unsplash.com/photo-1531415080290-bc98545ab2ef?auto=format&fit=crop&q=80&w=600",
      createdAt: 1784448000000
    },
    "news_3": {
      id: "news_3",
      headingEn: "Free Computer Literacy & Digital Learning Workshop",
      headingNp: "Free Computer Literacy & Digital Learning Workshop",
      bodyEn: "The FSU Academic Desk is hosting a 10-day Digital Literacy and ICT in Education workshop for all enrolled students. Learn research methodologies, presentation preparation, and online library access tools.",
      bodyNp: "Free Computer Literacy & Digital Learning Workshop",
      imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=600",
      createdAt: 1784361600000
    }
  },
  downloads: {
    "dl_1": {
      id: "dl_1",
      titleEn: "Farwestern University B.Ed Curriculum & Syllabus",
      titleNp: "Farwestern University B.Ed Curriculum & Syllabus",
      fileUrl: "https://fwu.edu.np",
      isDriveLink: true
    },
    "dl_2": {
      id: "dl_2",
      titleEn: "BBS Business Economics & Accounting Model Notes",
      titleNp: "BBS Business Economics & Accounting Model Notes",
      fileUrl: "https://fwu.edu.np",
      isDriveLink: true
    },
    "dl_3": {
      id: "dl_3",
      titleEn: "Campus Academic Calendar & Examination Timetable",
      titleNp: "Campus Academic Calendar & Examination Timetable",
      fileUrl: "https://fwu.edu.np",
      isDriveLink: true
    }
  },
  blogs: {
    "blog_1": {
      id: "blog_1",
      headingEn: "The Role of Youth in Remote Mountain Education",
      headingNp: "The Role of Youth in Remote Mountain Education",
      bodyEn: "Education in mountainous districts like Darchula has always faced geographical and infrastructural bottlenecks. However, with the rise of student leadership and digitalization, local youth are stepping up. By advocating for improved higher secondary facilities, promoting digital literacy, and engaging in constructive discourse, we are paving the path for future scholars.",
      bodyNp: "The Role of Youth in Remote Mountain Education",
      imageUrl: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=600",
      authorEn: "Amit Joshi, BBS Student",
      authorNp: "Amit Joshi, BBS Student",
      createdAt: 1784275200000
    },
    "blog_2": {
      id: "blog_2",
      headingEn: "Preserving Mahakali Border Culture and Heritage",
      headingNp: "Preserving Mahakali Border Culture and Heritage",
      bodyEn: "Our border region Darchula possesses a rich tapestry of culture, ranging from Gaura parva, Hudkeeli dance, to traditional folk tunes that echo the spirit of the Himalayas. In an era of globalization, we students must document these cultural gems, preserve our local history, and celebrate the natural splendor of the Mahakali basin.",
      bodyNp: "Preserving Mahakali Border Culture and Heritage",
      imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=600",
      authorEn: "FSU Cultural Committee",
      authorNp: "FSU Cultural Committee",
      createdAt: 1784188800000
    }
  },
  team: {
    "member_1": {
      id: "member_1",
      nameEn: "Amit Joshi",
      nameNp: "Amit Joshi",
      roleEn: "FSU President",
      roleNp: "FSU President",
      imageUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200",
      order: 1
    },
    "member_2": {
      id: "member_2",
      nameEn: "Janak Bahadur Dhami",
      nameNp: "Janak Bahadur Dhami",
      roleEn: "FSU Vice President",
      roleNp: "FSU Vice President",
      imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200",
      order: 2
    },
    "member_3": {
      id: "member_3",
      nameEn: "Deepa Tinkari",
      nameNp: "Deepa Tinkari",
      roleEn: "FSU Secretary",
      roleNp: "FSU Secretary",
      imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200",
      order: 3
    },
    "member_4": {
      id: "member_4",
      nameEn: "Suresh Sahu",
      nameNp: "Suresh Sahu",
      roleEn: "FSU Joint Secretary",
      roleNp: "FSU Joint Secretary",
      imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200",
      order: 4
    },
    "member_5": {
      id: "member_5",
      nameEn: "Karan Singh Badal",
      nameNp: "Karan Singh Badal",
      roleEn: "FSU Treasurer",
      roleNp: "FSU Treasurer",
      imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200",
      order: 5
    }
  },
  contacts: {},
  importantNotice: {
    active: true,
    titleEn: "FSU Student Academic & Admissions Help Desk",
    titleNp: "FSU Student Academic & Admissions Help Desk",
    bodyEn: "The Free Student Union - DMC has established a specialized Student Academic Help Desk on campus to support students in BBS, B.Ed, and BA programs. For inquiries regarding course syllabi, library resources, examination routines, or student welfare, contact the FSU Secretariat or visit the help desk.",
    bodyNp: "The Free Student Union - DMC has established a specialized Student Academic Help Desk on campus.",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=800",
    type: "both",
    bannerTextEn: "⚠️ CRITICAL CAMPUS ANNOUNCEMENT",
    bannerTextNp: "⚠️ CRITICAL CAMPUS ANNOUNCEMENT"
  },
  faqs: {
    "faq_1": {
      id: "faq_1",
      questionEn: "How can I obtain Farwestern University (FWU) course syllabi and lecture notes?",
      answerEn: "Students can download official FWU syllabi and curated lecture notes directly from the 'Syllabus & Notes' section of this portal. Physical course modules are also accessible at the DMC Central Library and the FSU Help Desk.",
      category: "Academic & Syllabus",
      order: 1,
      isPublished: true,
    },
    "faq_2": {
      id: "faq_2",
      questionEn: "How do I lodge an official grievance or appointment with the FSU Secretariat?",
      answerEn: "Navigate to the 'Contact Secretariat' page or the bottom Contact section. Fill in your details, select your issue category, and optionally attach supporting photos. You will instantly receive a unique Tracking Code (e.g., FSU-COMP-XXXXXX).",
      category: "Secretariat & Complaints",
      order: 2,
      isPublished: true,
    },
    "faq_3": {
      id: "faq_3",
      questionEn: "How can I track the progress and admin remarks of my submitted complaint?",
      answerEn: "Click on 'Track Your Complaint' in the footer or visit the /my-complaint URL. Enter your 10-character Tracking Code to view real-time status (Pending, In Review, In Progress, Resolved) and verified FSU executive remarks.",
      category: "Complaint Tracking",
      order: 3,
      isPublished: true,
    },
    "faq_4": {
      id: "faq_4",
      questionEn: "What scholarship schemes and financial aids are available at Darchula Multiple Campus?",
      answerEn: "DMC and FWU offer merit scholarships, student welfare subsidies, and government support for marginalized and remote students. Application deadlines and required recommendation forms are published under Campus Notices.",
      category: "Scholarships",
      order: 4,
      isPublished: true,
    },
    "faq_5": {
      id: "faq_5",
      questionEn: "How can students publish articles, opinions, or research on the Student Blogs platform?",
      answerEn: "Students can submit their written articles, literary pieces, or academic essays to the FSU Information & IT Department or through the Contact Secretariat form. Approved submissions are published on the 'Student Blogs' section.",
      category: "Student Life & Media",
      order: 5,
      isPublished: true,
    },
    "faq_6": {
      id: "faq_6",
      questionEn: "What should I do if I lose my College ID or Admit Card before exams?",
      answerEn: "Immediately report to the Campus Administration Block (Room 101) or the Examination Section head with proof of admission. The FSU Help Desk will assist you in expediting duplicate card verification.",
      category: "Examinations & Admin",
      order: 6,
      isPublished: true,
    },
  },
  trackingSettings: {
    headingEn: "FSU Student Complaint & Inquiry Tracker",
    subtitleEn: "Track the official review condition, workflow status, and FSU Secretariat remarks for your submissions in real time.",
    instructionsEn: "Enter your unique 10-character Tracking Code (e.g., FSU-COMP-XXXXXX) provided during complaint submission.",
    supportPhone: "9741823122",
    supportEmail: "info@fsudmc.com",
  },
  admins: {
    "admin_master": {
      id: "admin_master",
      username: "dmcadmin",
      role: "master",
      fullName: "Master Administrator (DMC)",
      createdAt: 1770000000000,
      status: "active",
      failedAttempts: 0,
    }
  },
  staff: {
    "staff-1": {
      id: "staff-1",
      name: "Janak Raj Pant",
      designation: "Campus Administrator",
      department: "Administration",
      email: "admin@fsudmc.com",
      phone: "+977-9848712345",
      office: "Main Administrative Block, Room 101",
      workingHours: "Sunday – Friday: 10:00 AM – 5:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300",
      status: "active",
      order: 1
    },
    "staff-2": {
      id: "staff-2",
      name: "Mohan Singh Dhami",
      designation: "Assistant Administrator",
      department: "Administration",
      email: "info@fsudmc.com",
      phone: "+977-9848712346",
      office: "Main Administrative Block, Room 102",
      workingHours: "Sunday – Friday: 10:00 AM – 5:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300",
      status: "active",
      order: 2
    },
    "staff-3": {
      id: "staff-3",
      name: "Birendra Bahadur Karki",
      designation: "Head of Examination Section",
      department: "Examination & Evaluation",
      email: "exam@fsudmc.com",
      phone: "+977-9848712347",
      office: "Academic Block 2, Examination Control Room",
      workingHours: "Sunday – Friday: 9:30 AM – 4:30 PM",
      imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300",
      status: "active",
      order: 3
    },
    "staff-4": {
      id: "staff-4",
      name: "Geeta Kumari Joshi",
      designation: "Examination Assistant",
      department: "Examination & Evaluation",
      email: "exam@fsudmc.com",
      phone: "+977-9848712348",
      office: "Academic Block 2, Room 204",
      workingHours: "Sunday – Friday: 10:00 AM – 4:30 PM",
      imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300",
      status: "active",
      order: 4
    },
    "staff-5": {
      id: "staff-5",
      name: "Khem Raj Bhatt",
      designation: "Senior Account Officer",
      department: "Finance & Accounts",
      email: "accounts@fsudmc.com",
      phone: "+977-9848712349",
      office: "Finance Wing, Ground Floor",
      workingHours: "Sunday – Friday: 10:00 AM – 4:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300",
      status: "active",
      order: 5
    },
    "staff-6": {
      id: "staff-6",
      name: "Prakash Singh Tinkari",
      designation: "Senior Librarian",
      department: "Library & Information Center",
      email: "library@fsudmc.com",
      phone: "+977-9848712350",
      office: "Central Campus Library, 1st Floor",
      workingHours: "Sunday – Friday: 8:00 AM – 5:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300",
      status: "active",
      order: 6
    },
    "staff-7": {
      id: "staff-7",
      name: "Sunita Bohara",
      designation: "Assistant Librarian",
      department: "Library & Information Center",
      email: "library@fsudmc.com",
      phone: "+977-9848712351",
      office: "Central Campus Library, Circulation Counter",
      workingHours: "Sunday – Friday: 9:00 AM – 4:30 PM",
      imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300",
      status: "active",
      order: 7
    },
    "staff-8": {
      id: "staff-8",
      name: "Dipendra Thapa",
      designation: "ICT & Systems Administrator",
      department: "ICT & Technical Support",
      email: "it@fsudmc.com",
      phone: "+977-9848712352",
      office: "Computer Lab & ICT Center, Room 301",
      workingHours: "Sunday – Friday: 9:00 AM – 5:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300",
      status: "active",
      order: 8
    }
  },
  professors: {
    "prof-1": {
      id: "prof-1",
      name: "Assoc. Prof. Dr. Dinesh Kumar Bhatt",
      title: "Campus Chief & Associate Professor",
      faculty: "Faculty of Management",
      department: "Business Administration & Strategy",
      qualification: "Ph.D. in Management, M.Phil, MBS",
      subjects: ["Strategic Management", "Organizational Behavior", "Business Research Methods"],
      researchInterests: "Higher Education Leadership, Mountain Regional Economic Development",
      bio: "Dr. Bhatt has over 18 years of academic leadership and research experience at Farwestern University, steering institution-building and regional economic studies.",
      email: "chief@fsudmc.com",
      officeHours: "Sunday – Thursday: 11:00 AM – 1:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400",
      status: "active",
      order: 1
    },
    "prof-2": {
      id: "prof-2",
      name: "Assoc. Prof. Ram Prasad Joshi",
      title: "Head of Department (Humanities)",
      faculty: "Faculty of Humanities & Social Sciences",
      department: "English & Linguistics",
      qualification: "M.Phil in English Literature, MA (Gold Medalist)",
      subjects: ["Modern English Poetry", "Critical Theory", "Academic Writing"],
      researchInterests: "Folk Literature of Farwestern Nepal, Border Studies",
      bio: "Leading the Humanities Department with a focus on cross-border literary archives and contemporary pedagogical criticism.",
      email: "faculty@fsudmc.com",
      officeHours: "Monday – Friday: 10:00 AM – 12:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
      status: "active",
      order: 2
    },
    "prof-3": {
      id: "prof-3",
      name: "Asst. Prof. Sunita Pant",
      title: "Head of Department (Education)",
      faculty: "Faculty of Education",
      department: "Curriculum and Pedagogy",
      qualification: "M.Ed in Curriculum & Evaluation",
      subjects: ["Educational Psychology", "Classroom Pedagogy", "Measurement & Evaluation"],
      researchInterests: "Inclusive Education in Mountain Communities, Gender and Literacy",
      bio: "Spearheading modern pedagogical practicum and inclusive community school teacher training across Darchula district.",
      email: "education@fsudmc.com",
      officeHours: "Sunday – Thursday: 1:00 PM – 3:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
      status: "active",
      order: 3
    },
    "prof-4": {
      id: "prof-4",
      name: "Asst. Prof. Kamal Singh Dhami",
      title: "Assistant Professor",
      faculty: "Faculty of Management",
      department: "Accountancy & Taxation",
      qualification: "MBS, Chartered Financial Auditor (CFA-Nepal)",
      subjects: ["Corporate Accounting", "Cost & Management Accounting", "Taxation in Nepal"],
      researchInterests: "Public Financial Management, SME Financing in Sudurpashchim",
      bio: "Expert in Nepalese tax legislation and corporate auditing, mentoring BBS cohorts in practical financial modeling.",
      email: "management@fsudmc.com",
      officeHours: "Sunday – Friday: 8:00 AM – 10:00 AM",
      imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400",
      status: "active",
      order: 4
    },
    "prof-5": {
      id: "prof-5",
      name: "Lecturer Bhupendra Bahadur Tinkari",
      title: "Lecturer in Economics",
      faculty: "Faculty of Humanities & Social Sciences",
      department: "Economics & Public Policy",
      qualification: "MA in Economics, Tribhuvan University",
      subjects: ["Microeconomics", "Macroeconomics", "Nepalese Economy & Planning"],
      researchInterests: "Cross-Border Trade with India & Tibet, Rural Livelihoods",
      bio: "Conducts empirical field research on Himalayan trade routes and economic development dynamics in high-altitude zones.",
      email: "economics@fsudmc.com",
      officeHours: "Monday – Thursday: 11:30 AM – 1:30 PM",
      imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
      status: "active",
      order: 5
    },
    "prof-6": {
      id: "prof-6",
      name: "Lecturer Pratima Bhatta",
      title: "Lecturer in Educational Administration",
      faculty: "Faculty of Education",
      department: "Educational Planning & Management",
      qualification: "M.Ed, B.Sc",
      subjects: ["Educational Administration & Supervision", "ICT in Education", "Action Research"],
      researchInterests: "Digital Pedagogy in Rural Schools, Teacher Professional Development",
      bio: "Focuses on technology integration in rural secondary schools and action research for teacher competency building.",
      email: "faculty@fsudmc.com",
      officeHours: "Sunday – Wednesday: 10:00 AM – 12:00 PM",
      imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400",
      status: "active",
      order: 6
    }
  },
  courses: {
    "course-bbs": {
      id: "course-bbs",
      titleEn: "Bachelor of Business Studies (BBS)",
      titleNp: "व्यवसाय अध्ययनमा स्नातक (BBS)",
      level: "Bachelor's Degree",
      faculty: "Faculty of Management",
      duration: "4 Years (Annual System)",
      descriptionEn: "The Bachelor of Business Studies (BBS) program under Farwestern University equips students with essential conceptual and practical knowledge in business management, accounting, banking, marketing, and entrepreneurship. The program emphasizes analytical thinking, ethical business leadership, and hands-on case studies relevant to the Nepalese economy.",
      eligibilityEn: "Completed +2 or equivalent in any discipline with minimum D+ / 45% aggregate score recognized by FWU.",
      careerProspects: "Banking & Financial Institutions, Corporate Enterprises, Accounting Firms, Civil Service, and Independent Business Entrepreneurship.",
      imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800",
      order: 1
    },
    "course-bed": {
      id: "course-bed",
      titleEn: "Bachelor of Education (B.Ed)",
      titleNp: "शिक्षाशास्त्रमा स्नातक (B.Ed)",
      level: "Bachelor's Degree",
      faculty: "Faculty of Education",
      duration: "4 Years (Annual System)",
      descriptionEn: "The 4-Year Bachelor of Education (B.Ed) program prepares professional, competent, and innovative educators across diverse specializations including Nepali, English, Health & Physical Education, and Social Studies. Emphasizes modern pedagogy, classroom management, and practical teaching practicum in community schools.",
      eligibilityEn: "Completed +2 or Higher Secondary Education in Education or any recognized stream.",
      careerProspects: "Secondary School Teachers, Educational Administrators, Curriculum Planners, NGO/INGO Educational Officers, and Researchers.",
      imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
      order: 2
    },
    "course-ba": {
      id: "course-ba",
      titleEn: "Bachelor of Arts (BA)",
      titleNp: "मानविकीमा स्नातक (BA)",
      level: "Bachelor's Degree",
      faculty: "Faculty of Humanities & Social Sciences",
      duration: "4 Years (Annual System)",
      descriptionEn: "A comprehensive multidisciplinary undergraduate program designed to cultivate critical thinking, socio-cultural understanding, and linguistic fluency. Major subject combinations include Sociology, English Literature, Nepali Literature, Economics, and Rural Development.",
      eligibilityEn: "Completed 10+2 / Intermediate level in any discipline.",
      careerProspects: "Public Administration, Journalism & Media, Social Research, Non-Governmental Organizations (NGOs), and Public Relations.",
      imageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=800",
      order: 3
    },
    "course-mbs": {
      id: "course-mbs",
      titleEn: "Master of Business Studies (MBS)",
      titleNp: "व्यवसाय अध्ययनमा स्नातकोत्तर (MBS)",
      level: "Master's Degree (Postgraduate)",
      faculty: "Faculty of Management",
      duration: "2 Years (Semester System)",
      descriptionEn: "The Master of Business Studies (MBS) is a rigorous postgraduate degree aimed at developing high-caliber managerial professionals, business strategists, and researchers. Focuses on advanced finance, strategic management, research methodology, and organizational behavior.",
      eligibilityEn: "Bachelor's Degree in Business Studies (BBS), BBA, or equivalent from FWU or recognized universities.",
      careerProspects: "Senior Corporate Executives, Bank Managers, Financial Analysts, College Lecturers, and Policy Consultants.",
      imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=800",
      order: 4
    },
    "course-med": {
      id: "course-med",
      titleEn: "Master of Education (M.Ed)",
      titleNp: "शिक्षाशास्त्रमा स्नातकोत्तर (M.Ed)",
      level: "Master's Degree (Postgraduate)",
      faculty: "Faculty of Education",
      duration: "2 Years (Semester System)",
      descriptionEn: "Advanced postgraduate specialization for visionary educators, educational researchers, and pedagogical leaders. Offers advanced focus on Educational Planning, Curriculum Development, and Specialized Subject Methodologies.",
      eligibilityEn: "Bachelor of Education (B.Ed) or One-Year B.Ed from any recognized university.",
      careerProspects: "Higher Secondary & University Faculty, Education Policy Specialists, Campus Administrators, and INGO Project Directors.",
      imageUrl: "https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&q=80&w=800",
      order: 5
    }
  }
};
